version: '3'

name: lowcode-data-mesh

services:
  biservice:
    image: metabase/metabase:latest
    restart: always
    env_file: ${BIENVFILE}
    depends_on:
    - "datacluster"
    - "proxy"

  appslowcode:
    ports:
      - 43000:3000
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    restart: always
    env_file: ${LOWCODEENVFILE}
    command: npm run start:prod
    depends_on:
      - "datacluster"
      - "proxy"
      - "smtpserver"

  graphql-mesh:
    image: hasura/graphql-engine:latest
    depends_on:
    - "datacluster"
    - "proxy"
    env_file: ${GRAPHQLMESHENVFILE}

  workflow:
    ports:
      - 41000:5678
    image: n8nio/n8n:latest
    env_file: ${WORKFLOWENVFILE}
    volumes:
      - wokflow-data:/home/node/.n8n
    depends_on:
    - "datacluster"
    - "proxy"
    - "smtpserver"

  nocodedb:
    ports:
      - 42000:8080
    image: nocodb/nocodb:latest
    env_file: ${TABLESENVFILE}
    restart: always
    volumes: 
      - ncdb-data:/usr/app/data
    depends_on:
    - "datacluster"
    - "proxy"
    - "smtpserver"

  datacluster:
    image: postgres:15
    env_file: ${PGENVFILE}
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    restart: always
    volumes:
      - dbcluster-data:/var/lib/postgresql/data

  dba-admin:
    image: dpage/pgadmin4
    env_file: ${PGADMINENVFILE}    
    volumes:
      - dba-data:/var/lib/pgadmin
    depends_on:
    - "datacluster"
    - "proxy"

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Port - TODO Disable This
    volumes:
      - proxy-data:/data
      - proxy-letsencrypt-data:/etc/letsencrypt

  smtpserver:
    image: mailhog/mailhog
    env_file: ${SMTPENVFILE}    
    volumes:
      - mail-data:/maildir
    depends_on:
      - proxy
      
volumes:
  proxy-data:
  mail-data:
  proxy-letsencrypt-data:
  dba-data:
  wokflow-data:
  dbcluster-data:  
  ncdb-data:
